apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      imagePullSecrets:
        - name: harbor-admin-registry
      containers:
      - name: demo-app
        image: harbor.mydomain.com/myproject/demo-app:1.0.0
        ports:
        - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      imagePullSecrets:
        - name: harbor-admin-registry
      containers:
      - name: demo-app
        image: harbor.mydomain.com/myproject/demo-app:1.0.0
        ports:
        - containerPort: 8080

